/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiPredictionsRouteImport } from './routes/ai-predictions'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BatteryStorageRouteImport } from './routes/battery-storage'
import { Route as ConsumersRouteImport } from './routes/consumers'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as EvChargingRouteImport } from './routes/ev-charging'
import { Route as PowerPlantsRouteImport } from './routes/power-plants'
import { Route as RenewablesRouteImport } from './routes/renewables'
import { Route as SubstationsRouteImport } from './routes/substations'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as TransmissionLinesRouteImport } from './routes/transmission-lines'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPredictionsRoute = AiPredictionsRouteImport.update({
  id: '/ai-predictions',
  path: '/ai-predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BatteryStorageRoute = BatteryStorageRouteImport.update({
  id: '/battery-storage',
  path: '/battery-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumersRoute = ConsumersRouteImport.update({
  id: '/consumers',
  path: '/consumers',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const EvChargingRoute = EvChargingRouteImport.update({
  id: '/ev-charging',
  path: '/ev-charging',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerPlantsRoute = PowerPlantsRouteImport.update({
  id: '/power-plants',
  path: '/power-plants',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewablesRoute = RenewablesRouteImport.update({
  id: '/renewables',
  path: '/renewables',
  getParentRoute: () => rootRouteImport,
} as any)
const SubstationsRoute = SubstationsRouteImport.update({
  id: '/substations',
  path: '/substations',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const TransmissionLinesRoute = TransmissionLinesRouteImport.update({
  id: '/transmission-lines',
  path: '/transmission-lines',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-predictions': typeof AiPredictionsRoute
  '/analytics': typeof AnalyticsRoute
  '/battery-storage': typeof BatteryStorageRoute
  '/consumers': typeof ConsumersRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/ev-charging': typeof EvChargingRoute
  '/power-plants': typeof PowerPlantsRoute
  '/renewables': typeof RenewablesRoute
  '/substations': typeof SubstationsRoute
  '/telemetry': typeof TelemetryRoute
  '/transmission-lines': typeof TransmissionLinesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-predictions': typeof AiPredictionsRoute
  '/analytics': typeof AnalyticsRoute
  '/battery-storage': typeof BatteryStorageRoute
  '/consumers': typeof ConsumersRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/ev-charging': typeof EvChargingRoute
  '/power-plants': typeof PowerPlantsRoute
  '/renewables': typeof RenewablesRoute
  '/substations': typeof SubstationsRoute
  '/telemetry': typeof TelemetryRoute
  '/transmission-lines': typeof TransmissionLinesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-predictions': typeof AiPredictionsRoute
  '/analytics': typeof AnalyticsRoute
  '/battery-storage': typeof BatteryStorageRoute
  '/consumers': typeof ConsumersRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/ev-charging': typeof EvChargingRoute
  '/power-plants': typeof PowerPlantsRoute
  '/renewables': typeof RenewablesRoute
  '/substations': typeof SubstationsRoute
  '/telemetry': typeof TelemetryRoute
  '/transmission-lines': typeof TransmissionLinesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-predictions'
    | '/analytics'
    | '/battery-storage'
    | '/consumers'
    | '/digital-twin'
    | '/ev-charging'
    | '/power-plants'
    | '/renewables'
    | '/substations'
    | '/telemetry'
    | '/transmission-lines'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-predictions'
    | '/analytics'
    | '/battery-storage'
    | '/consumers'
    | '/digital-twin'
    | '/ev-charging'
    | '/power-plants'
    | '/renewables'
    | '/substations'
    | '/telemetry'
    | '/transmission-lines'
  id:
    | '__root__'
    | '/'
    | '/ai-predictions'
    | '/analytics'
    | '/battery-storage'
    | '/consumers'
    | '/digital-twin'
    | '/ev-charging'
    | '/power-plants'
    | '/renewables'
    | '/substations'
    | '/telemetry'
    | '/transmission-lines'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiPredictionsRoute: typeof AiPredictionsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BatteryStorageRoute: typeof BatteryStorageRoute
  ConsumersRoute: typeof ConsumersRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  EvChargingRoute: typeof EvChargingRoute
  PowerPlantsRoute: typeof PowerPlantsRoute
  RenewablesRoute: typeof RenewablesRoute
  SubstationsRoute: typeof SubstationsRoute
  TelemetryRoute: typeof TelemetryRoute
  TransmissionLinesRoute: typeof TransmissionLinesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-predictions': {
      id: '/ai-predictions'
      path: '/ai-predictions'
      fullPath: '/ai-predictions'
      preLoaderRoute: typeof AiPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battery-storage': {
      id: '/battery-storage'
      path: '/battery-storage'
      fullPath: '/battery-storage'
      preLoaderRoute: typeof BatteryStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumers': {
      id: '/consumers'
      path: '/consumers'
      fullPath: '/consumers'
      preLoaderRoute: typeof ConsumersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ev-charging': {
      id: '/ev-charging'
      path: '/ev-charging'
      fullPath: '/ev-charging'
      preLoaderRoute: typeof EvChargingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-plants': {
      id: '/power-plants'
      path: '/power-plants'
      fullPath: '/power-plants'
      preLoaderRoute: typeof PowerPlantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renewables': {
      id: '/renewables'
      path: '/renewables'
      fullPath: '/renewables'
      preLoaderRoute: typeof RenewablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/substations': {
      id: '/substations'
      path: '/substations'
      fullPath: '/substations'
      preLoaderRoute: typeof SubstationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transmission-lines': {
      id: '/transmission-lines'
      path: '/transmission-lines'
      fullPath: '/transmission-lines'
      preLoaderRoute: typeof TransmissionLinesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiPredictionsRoute: AiPredictionsRoute,
  AnalyticsRoute: AnalyticsRoute,
  BatteryStorageRoute: BatteryStorageRoute,
  ConsumersRoute: ConsumersRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  EvChargingRoute: EvChargingRoute,
  PowerPlantsRoute: PowerPlantsRoute,
  RenewablesRoute: RenewablesRoute,
  SubstationsRoute: SubstationsRoute,
  TelemetryRoute: TelemetryRoute,
  TransmissionLinesRoute: TransmissionLinesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
